# Generated by Django 4.0.3 on 2022-03-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_group_city_alter_group_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='device_name',
            new_name='name',
        ),
    ]
