# Generated by Django 4.0.3 on 2022-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('template_content', models.TextField(blank=True)),
            ],
        ),
    ]
