# Generated by Django 4.0.3 on 2022-03-15 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
