# Generated by Django 4.0.3 on 2022-03-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0002_template_created_template_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
